# Generated by Django 5.1.6 on 2026-03-26 05:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=512)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("partial", "Partial Success"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed_rows", models.PositiveIntegerField(default=0)),
                ("error_rows", models.PositiveIntegerField(default=0)),
                (
                    "error_log",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="JSON-formatted log of row-level errors",
                    ),
                ),
                (
                    "processing_time_ms",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Total processing time in milliseconds",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin", models.CharField(db_index=True, max_length=255)),
                ("destination", models.CharField(db_index=True, max_length=255)),
            ],
            options={
                "ordering": ["origin", "destination"],
                "indexes": [
                    models.Index(
                        fields=["origin", "destination"], name="idx_route_pair"
                    )
                ],
                "unique_together": {("origin", "destination")},
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shipment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique shipment identifier from the source data",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("dispatch_date", models.DateField(db_index=True)),
                ("delivery_date", models.DateField(blank=True, null=True)),
                ("expected_delivery_date", models.DateField(blank=True, null=True)),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(db_index=True, default="other", max_length=50),
                ),
                (
                    "delay_days",
                    models.IntegerField(
                        default=0,
                        help_text="delivery_date - expected_delivery_date in days. Negative = early.",
                    ),
                ),
                (
                    "is_on_time",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="True if delivery_date <= expected_delivery_date",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipments",
                        to="shipments.route",
                    ),
                ),
                (
                    "upload",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shipments.uploadlog",
                    ),
                ),
            ],
            options={
                "ordering": ["-dispatch_date"],
                "indexes": [
                    models.Index(
                        fields=["dispatch_date", "is_on_time"],
                        name="idx_dispatch_ontime",
                    ),
                    models.Index(
                        fields=["vehicle_type", "dispatch_date"],
                        name="idx_vehicle_dispatch",
                    ),
                    models.Index(fields=["delivery_date"], name="idx_delivery_date"),
                ],
            },
        ),
    ]
