# Generated by Django 5.1.6 on 2026-03-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="amount_receivable",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Net amount receivable after deductions",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="charge_weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shipment",
            name="freight_deduction",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Freight deduction amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="gross_weight",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shipment",
            name="has_penalty",
            field=models.BooleanField(
                db_index=True, default=False, help_text="True if penalty > 0"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="has_shortage",
            field=models.BooleanField(
                db_index=True, default=False, help_text="True if shortage > 0"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="net_weight",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Net weight in metric tons",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="penalty",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Late delivery penalty amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="rate_per_mt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Rate per metric ton",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="shortage",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text="Shortage in metric tons",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Gross billing amount",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="transit_permissible",
            field=models.IntegerField(
                default=0, help_text="Permissible transit time in days (SLA)"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="transit_taken",
            field=models.IntegerField(
                default=0, help_text="Actual transit time in days"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle_no",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Vehicle registration number",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="uploadlog",
            name="data_quality_score",
            field=models.IntegerField(
                default=0, help_text="Data quality score 0–100 for this upload batch"
            ),
        ),
        migrations.AddField(
            model_name="uploadlog",
            name="duplicate_rows",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="uploadlog",
            name="quality_issues",
            field=models.TextField(
                blank=True, default="", help_text="JSON list of quality issues found"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="delay_days",
            field=models.IntegerField(
                default=0, help_text="transit_taken - transit_permissible"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="is_on_time",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique shipment identifier (C/N No.) from source data",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["has_shortage"], name="idx_has_shortage"),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(fields=["has_penalty"], name="idx_has_penalty"),
        ),
    ]
