# Generated by Django 5.2.12 on 2026-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0002_shipment_amount_receivable_shipment_charge_weight_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="billing_status",
            field=models.CharField(
                blank=True, default="", help_text="Status of the Billing", max_length=50
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pod_status",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Status of the Proof of Delivery",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="total_distance",
            field=models.FloatField(
                blank=True, help_text="Total transit distance in km", null=True
            ),
        ),
    ]
