# Generated by Django 5.2.12 on 2026-03-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0004_shipment_booking_region_shipment_contract_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="consignee_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="consignor_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
