# Generated by Django 5.2.12 on 2026-04-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_consignee_name_shipment_consignor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(db_index=True, max_length=255)),
                ('driver_phone', models.CharField(db_index=True, max_length=20)),
                ('truck_number', models.CharField(db_index=True, max_length=50)),
                ('date', models.DateField(db_index=True)),
                ('distance_travelled', models.DecimalField(decimal_places=2, default=0.0, help_text='Distance travelled so far today in km', max_digits=8)),
                ('expected_distance', models.DecimalField(decimal_places=2, default=300.0, help_text='Expected daily distance in km', max_digits=8)),
                ('last_updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date', 'driver_name'],
                'indexes': [models.Index(fields=['date'], name='idx_daily_log_date')],
                'unique_together': {('driver_phone', 'truck_number', 'date')},
            },
        ),
    ]
