# Generated by Django 5.1.6 on 2026-04-02 05:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0006_driverdailylog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("notification_type", models.CharField(default="info", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="DriverDailyLog",
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                help_text="Customer owning this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver assigned to this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
