# Generated by Django 5.1.6 on 2026-04-02 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "shipments",
            "0007_notification_delete_driverdailylog_shipment_customer_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="driver",
        ),
        migrations.AddField(
            model_name="shipment",
            name="assigned_driver",
            field=models.ForeignKey(
                blank=True,
                help_text="Driver user assigned to deliver this shipment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pod_file",
            field=models.FileField(
                blank=True,
                help_text="Proof of Delivery document uploaded by driver",
                null=True,
                upload_to="pod_uploads/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="pod_uploaded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when driver uploaded the POD",
                null=True,
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
