# Generated by Django 5.2.12 on 2026-04-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_remove_shipment_customer_remove_shipment_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='pod_image_1',
            field=models.ImageField(blank=True, help_text='POD photo 1 uploaded by driver', null=True, upload_to='pod_images/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_image_2',
            field=models.ImageField(blank=True, help_text='POD photo 2 (optional)', null=True, upload_to='pod_images/'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_image_3',
            field=models.ImageField(blank=True, help_text='POD photo 3 (optional)', null=True, upload_to='pod_images/'),
        ),
    ]
