# Generated by Django 5.2.12 on 2026-04-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_shipment_driver_name_shipment_driver_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='driver_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='driver_phone',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='invoice_url',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pod_uploaded',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pod_url',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='status',
        ),
    ]
