# Generated by Django 5.2.12 on 2026-04-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_remove_shipment_driver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='invoice_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_uploaded',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='shipment',
            name='pod_url',
            field=models.URLField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered')], db_index=True, default='pending', max_length=20),
        ),
    ]
