# Generated by Django 5.2.12 on 2026-04-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0012_shipment_driver_name_shipment_driver_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadlog",
            name="original_file",
            field=models.FileField(
                blank=True,
                help_text="The source data file (Excel or CSV)",
                null=True,
                upload_to="uploads/%Y/%m/",
            ),
        ),
    ]
