# Generated by Django 5.2.12 on 2026-04-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0013_uploadlog_original_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipment",
            name="assigned_driver",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="booking_region",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="consignee_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="consignor_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="contract_id",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="customer_name",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="invoice_url",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="material_type",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_file",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_image_1",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_image_2",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_image_3",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_uploaded",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_uploaded_at",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="pod_url",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="status",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="transporter_name",
        ),
    ]
