# Generated by Django 5.2.12 on 2026-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0014_remove_shipment_assigned_driver_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="booking_region",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="consignee_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="consignor_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="contract_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="shipment",
            name="customer_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="material_type",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="shipment",
            name="transporter_name",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=255
            ),
        ),
    ]
