# Generated by Django 5.2.12 on 2026-04-08 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0015_shipment_booking_region_shipment_consignee_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of the shipment record",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="uploadlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="The manager who uploaded this data",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
