# Generated by Django 5.2.12 on 2026-04-08 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0016_shipment_user_uploadlog_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shipments",
                to="shipments.uploadlog",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "dispatch_date"], name="idx_shipment_user_date"
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "is_on_time"], name="idx_shipment_user_ontime"
            ),
        ),
    ]
