# Generated by Django 5.2.12 on 2026-04-08 11:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0017_alter_shipment_upload_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["user", "shipment_id"], name="idx_shipment_user_sid"
            ),
        ),
    ]
