# Generated by Django 5.2.12 on 2026-04-08 11:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipments", "0018_shipment_idx_shipment_user_sid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="shipment",
            name="idx_shipment_user_date",
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="idx_shipment_user_ontime",
        ),
        migrations.RemoveIndex(
            model_name="shipment",
            name="idx_shipment_user_sid",
        ),
        migrations.AlterField(
            model_name="shipment",
            name="shipment_id",
            field=models.CharField(
                db_index=True,
                help_text="Unique shipment identifier (C/N No.) from source data",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="upload",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="shipments",
                to="shipments.uploadlog",
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("shipment_id", "user"), name="unique_user_shipment_id"
            ),
        ),
    ]
