# Generated by Django 5.2.12 on 2026-04-09 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0019_remove_shipment_idx_shipment_user_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sap_delivery_no', models.CharField(db_index=True, help_text='SAP Delivery Number — primary identifier from MIS report', max_length=100)),
                ('cn_date', models.DateField(db_index=True, help_text='Consignment date')),
                ('pod_date', models.DateField(blank=True, help_text='Proof of delivery date', null=True)),
                ('booking_branch', models.CharField(blank=True, default='', max_length=255)),
                ('loading_state', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('loading_city', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('delivery_state', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_city', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('customer_name', models.CharField(blank=True, default='', max_length=512)),
                ('consignor', models.CharField(blank=True, default='', max_length=512)),
                ('consignee_name', models.CharField(blank=True, default='', max_length=512)),
                ('service_agent', models.CharField(blank=True, default='', max_length=255)),
                ('contract_owner', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_type', models.CharField(blank=True, default='', max_length=100)),
                ('material_name', models.CharField(blank=True, default='', max_length=255)),
                ('contract_type', models.CharField(blank=True, default='', max_length=100)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('charge_weight', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('distance', models.IntegerField(default=0)),
                ('value_of_goods', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fleet_freight', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lorry_hire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lorry_hire_topf', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('own_fleet_exp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rake_exp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('freight_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('extra_lorry_hire', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transhipment_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm1', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm1_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('freight_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('operational_other_income', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labour', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wages', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('insurance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_direct_exp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('lrp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm2', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm2_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('reimb_exp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm3', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('claim', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detention', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ldp', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('other_operation_ded', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm4', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm5', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm5_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('cash_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transaction_charges', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('pli', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('broker_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('petro_incentive', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm6', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('gm6_pct', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('gm7', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('projected_margin', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-cn_date'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='shipment',
            name='unique_user_shipment_id',
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipment_id',
            field=models.CharField(db_index=True, help_text='Unique shipment identifier (C/N No.) from source data', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='upload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profit_records', to='shipments.uploadlog'),
        ),
        migrations.AddField(
            model_name='profitrecord',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='profitrecord',
            index=models.Index(fields=['cn_date', 'loading_city', 'delivery_city'], name='idx_profit_lane_date'),
        ),
        migrations.AddIndex(
            model_name='profitrecord',
            index=models.Index(fields=['loading_city', 'delivery_city'], name='idx_profit_lane'),
        ),
    ]
