# Generated by Django 5.2.12 on 2026-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_profitrecord_remove_shipment_unique_user_shipment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profitrecord',
            name='sap_external_no',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SAP External Number from MIS report', max_length=100),
        ),
    ]
