# Generated by Django 5.2.12 on 2026-04-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_otprecord_alter_userprofile_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="vehicle_no",
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[("general", "General")],
                db_index=True,
                default="general",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Mobile number used for OTP login",
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[("manager", "Branch Manager / Employee")],
                db_index=True,
                default="manager",
                max_length=20,
            ),
        ),
    ]
